version: "3.7"
services:
  backend:
    build: .
    restart: always
    ports:
      - 8080:8080
    expose:
      - 8080
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/endpointmonitoring
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: pass
    networks:
      - app-db
    depends_on:
      mysql:
          condition: service_healthy
  mysql:
    image: mysql:8.0
    restart: always
    ports:
      - 3306:3306
    expose:
      - 3306
    environment:
      MYSQL_DATABASE: endpointmonitoring
      MYSQL_USER: user
      MYSQL_PASSWORD: pass
      MYSQL_ROOT_PASSWORD: pass
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - app-db
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "--silent" ]
      interval: 3s
      retries: 5
      start_period: 30s
volumes:
  mysql-data: {}
networks:
  app-db: {}